# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ERANHER/programs/clion-2019.3.2/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/ERANHER/programs/clion-2019.3.2/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ERANHER/eran/repo/track_racing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ERANHER/eran/repo/track_racing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/ERANHER/programs/clion-2019.3.2/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/ERANHER/programs/clion-2019.3.2/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ERANHER/eran/repo/track_racing/CMakeFiles /home/ERANHER/eran/repo/track_racing/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ERANHER/eran/repo/track_racing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named track_racing

# Build rule for target.
track_racing: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 track_racing
.PHONY : track_racing

# fast build rule for target.
track_racing/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/build
.PHONY : track_racing/fast

Agent.o: Agent.cpp.o

.PHONY : Agent.o

# target to build an object file
Agent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/Agent.cpp.o
.PHONY : Agent.cpp.o

Agent.i: Agent.cpp.i

.PHONY : Agent.i

# target to preprocess a source file
Agent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/Agent.cpp.i
.PHONY : Agent.cpp.i

Agent.s: Agent.cpp.s

.PHONY : Agent.s

# target to generate assembly for a file
Agent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/Agent.cpp.s
.PHONY : Agent.cpp.s

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/Game.cpp.s
.PHONY : Game.cpp.s

Grid.o: Grid.cpp.o

.PHONY : Grid.o

# target to build an object file
Grid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/Grid.cpp.o
.PHONY : Grid.cpp.o

Grid.i: Grid.cpp.i

.PHONY : Grid.i

# target to preprocess a source file
Grid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/Grid.cpp.i
.PHONY : Grid.cpp.i

Grid.s: Grid.cpp.s

.PHONY : Grid.s

# target to generate assembly for a file
Grid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/Grid.cpp.s
.PHONY : Grid.cpp.s

MdpPlaner.o: MdpPlaner.cpp.o

.PHONY : MdpPlaner.o

# target to build an object file
MdpPlaner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/MdpPlaner.cpp.o
.PHONY : MdpPlaner.cpp.o

MdpPlaner.i: MdpPlaner.cpp.i

.PHONY : MdpPlaner.i

# target to preprocess a source file
MdpPlaner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/MdpPlaner.cpp.i
.PHONY : MdpPlaner.cpp.i

MdpPlaner.s: MdpPlaner.cpp.s

.PHONY : MdpPlaner.s

# target to generate assembly for a file
MdpPlaner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/MdpPlaner.cpp.s
.PHONY : MdpPlaner.cpp.s

State.o: State.cpp.o

.PHONY : State.o

# target to build an object file
State.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/State.cpp.o
.PHONY : State.cpp.o

State.i: State.cpp.i

.PHONY : State.i

# target to preprocess a source file
State.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/State.cpp.i
.PHONY : State.cpp.i

State.s: State.cpp.s

.PHONY : State.s

# target to generate assembly for a file
State.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/State.cpp.s
.PHONY : State.cpp.s

headers/Policy/RTDP_util.o: headers/Policy/RTDP_util.cpp.o

.PHONY : headers/Policy/RTDP_util.o

# target to build an object file
headers/Policy/RTDP_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/headers/Policy/RTDP_util.cpp.o
.PHONY : headers/Policy/RTDP_util.cpp.o

headers/Policy/RTDP_util.i: headers/Policy/RTDP_util.cpp.i

.PHONY : headers/Policy/RTDP_util.i

# target to preprocess a source file
headers/Policy/RTDP_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/headers/Policy/RTDP_util.cpp.i
.PHONY : headers/Policy/RTDP_util.cpp.i

headers/Policy/RTDP_util.s: headers/Policy/RTDP_util.cpp.s

.PHONY : headers/Policy/RTDP_util.s

# target to generate assembly for a file
headers/Policy/RTDP_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/headers/Policy/RTDP_util.cpp.s
.PHONY : headers/Policy/RTDP_util.cpp.s

headers/Policy/RtdpAlgo.o: headers/Policy/RtdpAlgo.cpp.o

.PHONY : headers/Policy/RtdpAlgo.o

# target to build an object file
headers/Policy/RtdpAlgo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/headers/Policy/RtdpAlgo.cpp.o
.PHONY : headers/Policy/RtdpAlgo.cpp.o

headers/Policy/RtdpAlgo.i: headers/Policy/RtdpAlgo.cpp.i

.PHONY : headers/Policy/RtdpAlgo.i

# target to preprocess a source file
headers/Policy/RtdpAlgo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/headers/Policy/RtdpAlgo.cpp.i
.PHONY : headers/Policy/RtdpAlgo.cpp.i

headers/Policy/RtdpAlgo.s: headers/Policy/RtdpAlgo.cpp.s

.PHONY : headers/Policy/RtdpAlgo.s

# target to generate assembly for a file
headers/Policy/RtdpAlgo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/headers/Policy/RtdpAlgo.cpp.s
.PHONY : headers/Policy/RtdpAlgo.cpp.s

headers/serach/Astar.o: headers/serach/Astar.cpp.o

.PHONY : headers/serach/Astar.o

# target to build an object file
headers/serach/Astar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/headers/serach/Astar.cpp.o
.PHONY : headers/serach/Astar.cpp.o

headers/serach/Astar.i: headers/serach/Astar.cpp.i

.PHONY : headers/serach/Astar.i

# target to preprocess a source file
headers/serach/Astar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/headers/serach/Astar.cpp.i
.PHONY : headers/serach/Astar.cpp.i

headers/serach/Astar.s: headers/serach/Astar.cpp.s

.PHONY : headers/serach/Astar.s

# target to generate assembly for a file
headers/serach/Astar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/headers/serach/Astar.cpp.s
.PHONY : headers/serach/Astar.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/main.cpp.s
.PHONY : main.cpp.s

util_game.o: util_game.cpp.o

.PHONY : util_game.o

# target to build an object file
util_game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/util_game.cpp.o
.PHONY : util_game.cpp.o

util_game.i: util_game.cpp.i

.PHONY : util_game.i

# target to preprocess a source file
util_game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/util_game.cpp.i
.PHONY : util_game.cpp.i

util_game.s: util_game.cpp.s

.PHONY : util_game.s

# target to generate assembly for a file
util_game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/track_racing.dir/build.make CMakeFiles/track_racing.dir/util_game.cpp.s
.PHONY : util_game.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... track_racing"
	@echo "... Agent.o"
	@echo "... Agent.i"
	@echo "... Agent.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... Grid.o"
	@echo "... Grid.i"
	@echo "... Grid.s"
	@echo "... MdpPlaner.o"
	@echo "... MdpPlaner.i"
	@echo "... MdpPlaner.s"
	@echo "... State.o"
	@echo "... State.i"
	@echo "... State.s"
	@echo "... headers/Policy/RTDP_util.o"
	@echo "... headers/Policy/RTDP_util.i"
	@echo "... headers/Policy/RTDP_util.s"
	@echo "... headers/Policy/RtdpAlgo.o"
	@echo "... headers/Policy/RtdpAlgo.i"
	@echo "... headers/Policy/RtdpAlgo.s"
	@echo "... headers/serach/Astar.o"
	@echo "... headers/serach/Astar.i"
	@echo "... headers/serach/Astar.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... util_game.o"
	@echo "... util_game.i"
	@echo "... util_game.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

